/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6 for MT6592. Copyright MediaTek Inc. (C) 2013.
 * Tue Jul  7 13:13:26 2015
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H


#define AUXADC_LCM_VOLTAGE_CHANNEL     0
#define AUXADC_ADC_FDD_RF_PARAMS_DYNAMIC_CUSTOM_CH_CHANNEL     13


#endif //_CUST_AUXADC_TOOL_H


