/*
 * Generated by MTK SP DrvGen Version 03.13.6  for MT6592. Copyright MediaTek Inc. (C) 2013.
 * Tue Jul  7 13:13:27 2015
 * Do Not Modify the File.
 */

#define CUST_EINT_MD_LEVEL_SENSITIVE        0
#define CUST_EINT_MD_EDGE_SENSITIVE         1




#define CUST_EINT_POLARITY_LOW              0
#define CUST_EINT_POLARITY_HIGH             1
#define CUST_EINT_EDGE_SENSITIVE            0
#define CUST_EINT_LEVEL_SENSITIVE           1




#define CUST_EINT_MD1_2_NAME             "MD1_SIM1_HOT_PLUG_EINT"
#define CUST_EINT_MD1_2_NUM              2
#define CUST_EINT_MD1_2_DEBOUNCE_CN      100
#define CUST_EINT_MD1_2_POLARITY         CUST_EINT_POLARITY_HIGH
#define CUST_EINT_MD1_2_SENSITIVE        CUST_EINT_MD_LEVEL_SENSITIVE
#define CUST_EINT_MD1_2_DEBOUNCE_EN      CUST_EINT_DEBOUNCE_ENABLE

#define CUST_EINT_MD1_CNT      1


